sudo: enabled
before_install:
- sudo apt-get -qq update
- sudo apt-get -y install texlive-latex-base
- sudo apt-get -y install texlive-fonts-recommended
- sudo apt-get -y install texlive-fonts-extra
- sudo apt-get -y install texlive-latex-extra
- sudo apt-get -y install s3cmd
script:
- "./deploy"
env:
  global:
  - secure: vfyMp2zAuwKfHgGTOrpoF6IdbvRvLKhKHELW3CbNP8THvhFyLY7YgvX603+1ss61ftUkAXnqZBTyARwvfJ0BgjuLbfGpHBB/O+PGuNMWShXbvtgcDNgJfz8xW4fPzD9R41/K0V5yVFR1LtcLVihRc38509dCTtBmjOwMVR8fcQUL9mjamQGvV8MrgJts1Qi6h0N6z/gtUB2lWh76CvdMMtcLAR+k570g97Z5lB8yv+MPfkpajecnG9LFfeHIVOryQs3/gF0OQaBO4+Nv//sNbDYHZ3LTiQgulpngxElb2BWxeGn7R9PioU/bdaLiqOnKf+0TvdFb8PS29qtZG92ml4ZyShJqzAoNf4PGpJMVznJes2Zi5suzyBaPvykHt4Wmus5ZK+4r4C/afc9mxDfSvhGcSlftIZwbuLTo/0V3rNgIL/3aUOZb0v7AA784Jm7adyDfCtTUt3HQFew8jTQxH5JODOm98wlsqa3txxIQdMu1qq/k5Fh2wqVxGL2XJrJUcGknm1Xfa1cGf+RlH3dQOfBIyO++/F4sV636zCEJKViAz6ong8Jjvml+HjGcIw/TbLJkjGJBEMt9ZJeZhG+mp8KNaakuIaua68INhRaKeJ57MHpLiyvFMS76b3PK3MWOM8Gg/tneIEVvZdn/yVKiut66NNfFaxkLtBNeIeNBpO4=
  - secure: sgd3ZB5CXZSQX+ZaHv9Nl3Su/iYYtXfPqIVd3YtrpNZA4YsNRVS2nzWHaW/DbeGhxEvVuFtGtULNjBbQ3KqWjWDeElaow2h56t7VKaTUzrZIwZkhkTVxuqeBSnt05loRBBJZ82uGr1Z4XGJ0GUFSsn1cZnRQyoFQjjNEXiFO+NQXZ23GpaNwmTCjIOqzU5HIwgvlOIbyCzH8KsOXRrI9eA8v9CFD6OC88w7xqk4Ewf49lpCMaQ6VSc5mxuLR9eBvnRWLlpS/FI9IH2hhDwXUPEul+ggrqWa1fgRusYzS7cxGCASWli7HYLeW9Rhcnj9SUZpwWaA7CR9FbwdaFvHdykAi06rox+mfNnvW8sqreannhimUJepuYcdSJCE2sJb8o3pO0NUC9mdw14Yu8A08pleZmxLqkXMfviKDpm7XqwFjG1QgRbmPOmoaB9dxKqFLD1CRHGPI9qQEXyoI9A+s4diswAk19C9vrXOIXwaOVBHlO7Htgw0WfpHOT2lbY9RthH4vS6svqQzQIa2corodddFdSRAthWBoAFXXMJqeHbKlzkp5bnNDIsl5vMCUmIZNLPqucvqmvFZZGx8qe1ykMjz0r3FJRLPIchHpoFShTX+jtq5NaNu0lNK4C7V8SBxLop3hm7C6uLfCZ9B30MlujqMYwkobfxVlk+pO5ZkHjV0=
