#!/bin/bash
set -e

if [ "$CI" = true ]; then
  branch=$CI_BRANCH_NAME
  if [ "$branch" == "master" ]; then
    prefix=""
  else
    prefix="testing/"
  fi
else
  branch=$(git rev-parse --abbrev-ref HEAD)
  prefix="testing/local/"
fi

make resume
aws s3 cp resume.pdf "s3://ben-muschol-resume/$prefix$branch.pdf" --acl public-read
make clean
